@isTest
private class ReferralRestControllerTest {
	static testMethod void referralRestControllerTestdelete(){
        /*
		//Assign Record Id
		Id recordId = '';
		// Set up a test request
		RestRequest request = new RestRequest();
		request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/RESTAPICLASSURL/'+ recordId;
		request.httpMethod = 'GET';
		RestContext.request = request;
		// Call the method to test
        <REST API Class Name>.delete();
        */
	}
}